% function plotDashMan(D)
%
% Plots the content of a dash-man struct.
%
% --- Input ---
% 1. "D" - Dash-man object, as generated by DashMan.m.
% 
% See also DashMan
%
% By Thomas Jonsson, 2023
%
function plotDashMan(D)

plot( D.head(1,:)  , D.head(2,:)  ,'linewidth', 2)
hold on
plot( D.mouth(1,:) , D.mouth(2,:) ,'linewidth', 2)
plot( D.body(1,:)  , D.body(2,:)  ,'linewidth', 2)
plot( D.legs(1,:)  , D.legs(2,:)  ,'linewidth', 2)
plot( D.arms(1,:)  , D.arms(2,:)  ,'linewidth', 2)

